services:
  bot:
    build: ./bot
    env_file: .env
    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./data/done:/data/done
    depends_on:
      - demucs
    restart: unless-stopped

  demucs:
    build: ./demucs
    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./data/done:/data/done
    restart: unless-stopped
